
language: go
go:
  - 1.5.3
  - 1.6
  - tip
env:
  global:
    - BUILD_GOARCH=amd64
  matrix:
    - BUILD_GOOS=linux
    - BUILD_GOOS=darwin
    - BUILD_GOOS=windows
script:
  - go build
  - go vet ./...
  - go test -i -race ./...
  - go test -v -race ./...

