language: go

go:
  - 1.6
  - 1.7
  - tip

os:
  - linux
  - osx

env:
  matrix:
    - BUILD_GOARCH=amd64
    - BUILD_GOARCH=386

before_install:
  - go get -u honnef.co/go/simple/cmd/gosimple

# don't go get deps. will only build with code in vendor directory.
install: true

script:
  # pkgs avoids testing anything in vendor/
  - pkgs=$(go list ./... | grep -v /vendor/)
  - go vet $pkgs
  - go test -v -race $pkgs
  - gosimple $pkgs
