
language: go
go:
  - 1.5.4
  - 1.6.2
  - tip
os:
  - linux
  - osx
env:
  matrix:
    - BUILD_GOARCH=amd64
    - BUILD_GOARCH=386
script:
  - go build
  - go vet ./...
  - go test -i -race ./...
  - go test -v -race ./...

